In [1]:
!pip install numpy


   ---------------------------------------- 0.0/12.4 MB ? eta -:--:--
   ---------------------------------------- 0.0/12.4 MB ? eta -:--:--
   ---------------------------------------- 0.0/12.4 MB ? eta -:--:--
   -- ------------------------------------- 0.8/12.4 MB 3.6 MB/s eta 0:00:04
   ---------- ----------------------------- 3.4/12.4 MB 8.3 MB/s eta 0:00:02
   -------------------------------- ------- 10.0/12.4 MB 16.2 MB/s eta 0:00:01
   ---------------------------------------- 12.4/12.4 MB 17.5 MB/s  0:00:01


In [3]:
import numpy as np

In [4]:
arr1 = np.arange(1, 11)
print(arr1)

arr2 = np.random.randint(1, 10, size=(3, 3))
print(arr2)

[ 1  2  3  4  5  6  7  8  9 10]
[[7 2 9]
 [3 9 7]
 [4 8 8]]


In [5]:
print("Sum:", arr1.sum())
print("Mean:", arr1.mean())
print("Max:", arr1.max())

arr_multiplied = arr1 * 2
print(arr_multiplied)

arr_replaced = np.where(arr1 > 5, 0, arr1)
print(arr_replaced)

Sum: 55
Mean: 5.5
Max: 10
[ 2  4  6  8 10 12 14 16 18 20]
[1 2 3 4 5 0 0 0 0 0]
